### ISSUE TITLE
End date of the active data base has passed .

### ISSUE THREAD

**Issue by dudsha** [Heavy-Division/B78XH#179]
I got in the FMC this note:
"End date of the active data base has passed select new cycle on IDENT page"

Wher is the IDENT page ?

**Comment by ace1194** [comment]
i get the same, i have a full navigraph sub and should be able to one click update, but when i find the ident page, the update bit, i forget what it says, its blanked out, cant click.

**Comment by jrykowski55** [comment]
I have the same problem using the mod in MSFS.  I'm assuming this is a data entry error.  The months and days look fine, but the year is 2021 instead of 2022.  None of the fields on the IDENT page are clickable, so I have no way to fix this, and it will not accept a flight plan without a valid end date. Please help.

**Comment by MicahBCode** [comment]
@dudsha @ace1194 @jrykowski55 Does the problem still exist with the latest release (v.0.1.13) installed?

**Comment by nakajimayoshi** [comment]
@dudsha Unless you own a navigraph subscription you will likely be using an out of date AIRAC cycle. This message occurs on the IRL B787 and can be safely ignored if you don't have a navigraph subscription

**Comment by dudsha** [comment]
? ? ?

בתאריך יום ו׳, 4 בנוב׳ 2022, 08:57, מאת nakajimayoshi ‏<
***@***.***>:
