### ISSUE TITLE
B787-10

### ISSUE THREAD

**Issue by KalTiwana** [Heavy-Division/B78XH#208]
The APU does not start when the Centre Tanks fuel pumps are switched on.  If the APU is running, switching the Centre Tanks pumps ON switches the APU off.  Additionally, there is no Sim Rate manager visible in HEAVY selection on the CDU.

**Comment by Hypeism** [comment]
The centre fuel pumps switching off the APU is a feature, not a bug: 

1) APU uses fuel from "L AFT pump"
2) B787 priorities for fuel/pumps are: L CENTER, L AFT, L FWD and R CENTER, R AFT, R FWD

Under the hood:

The APU works normally with L AFT pump turned on and L CENTER pump turned off (or in PRESS state). if you turn L CENTER pump on the B787 cut off fuel flow through L AFT and L FWD. This behavior is because of the pumps priorities. L CENTER pump has higher priority than L AFT/FWD pumps and B787 cut off the pumps internally to prevent the aircraft uses fuel from left main tank.

The APU shut down or does not start with L CENTER pump turned on because the APU uses the L AFT pump exclusively. (L AFT/FWD pumps are turned on for a user [on overhead panel] but internally they are in "stand by mode" because a fuel pump with higher priority is turned on)

**Comment by KalTiwana** [comment]
Thanks for your information about 787 fuel pumps.  I do not have experience
on Boeing 787.  I assisted the other member purely by my experience on
other Boeing models where the APU does not shut down with centre pumps
running.

Other Boeing models have higher capacity centre pumps in order to empty the
centre tanks first.  This is to reduce stress on the wings.  I now know
that 787 does the same thing by switching the wing tank pumps off when the
centre tank pumps are operating.  This is nice to know and thank you. You
learn something everyday.

I hope that you inform other simmers who are getting flustered as to why
the APU shuts down with centre tank pumps operating.

Regards

VForce
