### ISSUE TITLE
ELEC Synoptic Page - from the abandoned B787-XE mod and merge into B78XH?

### ISSUE THREAD

**Issue by NeosDumb** [Heavy-Division/B78XH#227]
Hi Heavy Division, love the mod for the B78X, before this was released I was using the B787-XE mod; but when this came out with all its extra features there was no choice but to make the switch.

The only thing I have been missing from the abandoned B787-XE mod (https://github.com/lmk02/B787-XE) is the ELEC synoptic page which they had fully modelled and coded to work as it should.

As that project has been abandoned 16 months ago, and the author even provides a link to your Heavy Division B78XH; but I was hoping that from that older project, you could take the already modelled and coded ELEC Synoptic Page and merge it into your B78XH mod.

I have suggested this many time through various avenues: Flightsim.to comments and the Heavy Division discord but the suggestion doesn't seem to have been picked up, and I have been waiting patiently for over a year and a half.

So I was hoping this could be a really quick and easy thing to do, and hope it can be something in your next update.

Thank you in advance.

**Comment by lmk02** [comment]
I can take care of it. Just need to check if it's still working and compatible with the latest changes. Should be done in no time

**Comment by NeosDumb** [comment]
Where are we up to on this one, I thought that this was completed and awating some checks, changes and then merging?

**Comment by nakajimayoshi** [comment]
@NeosDumb Apologies for the late response. There's several reasons we did not adopt the XE's implementation of the ELEC page.

1) The displays and aircraft systems are being refactored such that they are rendered from a C++ WASM module instead of Javascript


2) The implementation of the XE's ELEC page isn't optimal (use of deprecated var keyword and excessive use of if..else statements) 


3) We're more interested in creating accurate systems than interactive displays based on the inaccurate default Asobo code. The electrical system for example is lacking most of the aircraft's AC buses, the APU battery, and many more connections and items. We will add the pages back when they are in a production ready state, but for now our focus is on refactoring the displays to the WASM module. You can find it at https://github.com/Heavy-Division/B78XH-wasm
