### ISSUE TITLE
ILS Auto tuning not working when choosing NEW ARR

### ISSUE THREAD

**Issue by ImPlasmaTbh** [Heavy-Division/B78XH#237]
### Aircraft Version

Development

### Build info

```json
{
    "package_version": "0.1.15-5",
    "fms_man_version": "HD-P000-1-15-5",
    "fms_bak_version": "HD-C000-1-15-5"
}
```

### Describe the bug

When you change your arrival runway to an airport, ILS frequency no longer auto tunes.

### Expected behavior

ILS frequency will tune to the frequency of the new arrival runway

### Steps to reproduce

1. Set arrival into airport (Eg. ILS 8R into Miami)
2. Go to NAV RAD page - you will notice that the ILS frequency is auto tuned
3. Change arrival into same airport (Eg. Now ILS 8R into Miami has changed to ILS 22R into Miami)
4. Go to NAV RAD PAGE - ILS frequency is not tuned automatically.

### Additional info (optional)

The "KNOWN ISSUES" page acknowledges this bug and says that "SOMETIMES" the aircraft may not tune into the runway ILS frequency however in my case it always tunes into the runway frequency unless you change the arrival.

### Discord Username (optional)

ImPlasmaTbh#2079

**Comment by nakajimayoshi** [comment]
Can you also share the STARs you input into Miami? Thanks

**Comment by nakajimayoshi** [comment]
![image](https://user-images.githubusercontent.com/52870481/198298824-96e8a64d-c76f-45b5-bb0f-c6dd037d97f4.png)
I have a theory after some extensive testing. I think this issue is more related to the mouse click resolver than the FMC. 

Sometimes the mousclicks don't resolve properly, and you end up with a green EXEC button when the ILS hasn't been selected yet , which could lead to the frequency not being filled in automatically.

If possible, could you try entering the exact same approaches, but confirming that a <SEL> is next to the ILS approach you select, similar to the picture above, and report back if the ILS frequencies are entered for KMIA? I was able to successfully get all ILS frequencies automatically entered for Miami.
