### ISSUE TITLE
787XH Mod does not work with Avionics Update 02 (6/22/2023)

### ISSUE THREAD

**Issue by d3wg** [Heavy-Division/B78XH#298]
### Aircraft Version

Stable

### Build info

```json
{
    "package_version": "0.1.15",
    "fms_man_version": "HD-P000-1-15-STA",
    "fms_bak_version": "HD-C000-1-15-BAK"
}
```

### Describe the bug

When starting up the 787XH mod from the Heavy division team, the plane seems not to be compatible with the new update. When starting the 787-10 (with the Heavy Division mod) after turning on the Battery in the Electrical part of the overhead panel and then turning on the external power, it has seemed that the external power did not want to turn on :(. Therefore I could not start up the plane from it's cold and dark stage.

### Expected behavior

I've I expected for the external power to turn on in the 787-10 Heavy division mod so I could complete the startup from cold and dark and continue with my flight.

### Steps to reproduce

1. Startup Microsoft Flight Simulator 2020 with the new Avionics Update 02 that was released on 6/22/2023 (Make sure to update your driver if need and recommend by the Flight Simulator)
2. Spawn the 787-10 (with the latest Heavy Division Mod Stable) in the cold and dark stage of the aircraft (At a ramp or a gate)
3. Try doing the normal startup for the 787-10 and you will notice bugs when starting up using the external power supply.

### Additional info (optional)

I expected that too happened because the Heavy Division Mod (stable) was not compatible with the new Avionics update for the 787. (I really like what the Heavy division team has done, and it's far better than what Microsoft has done)

**Comment by crzran** [comment]
I also encountered this bug today

**Comment by cptkasskah** [comment]
Hi,
Same issue for me today.

**Comment by rGustave07** [comment]
Same here, but also, the auto throttle switch doesn't turn on and the throttle itself while the value does change when I change it on my input, in-game it visually stays at 0%.

**Comment by SteveiM63** [comment]
I have this issue as well. its a pity because this is a really great aircraft. I deleted it from the community folder then installed the experimental version. all works great, with exception to the main feature, no HEAVY switch on the FMC so you cant migrate the Sim brief plan. I guess I will have to buy the PMDG 737-800. still a pity though. I don't suppose there is a work around?

**Comment by PrimalRF** [comment]
I found the solution you need to bind the key for the external power and it will work!

**Comment by cptkasskah** [comment]
Hi,
Don't understand...what did you mean by "bind the key" ?
Can you be more precise ?
May be a picture can help.
Thx

**Comment by dbryant69** [comment]
I have exactly the same problem. external power will not switch on and neither will auto throttle. External power shows available after battery is switched on but will not go further.

**Comment by Barbecuerex** [comment]
I have the  same problems with this plane since the update.

**Comment by nakajimayoshi** [comment]
We announced on Discord but we don't recommend using B78XH as of the SU13 beta since we are far behind the default now in terms of features. We're not going away, but will need to put a pause on all support & non-development related projects until we have an aircraft that exceeds the quality of the default.
